{{! -----------------------------------
	JSON master template for RHC message
	It is used to construct the final JSON message to send to server
	It aggregates all partial JSON messages that were sampled periodically

	xmo requests needed :
	- Device/DeviceInfo
	- Device/Ethernet/Links/Link
	- Device/IP/Interfaces/Interface[Alias='IP_DATA']
	--------------------------------------- }}
{
	"msg_version": 3,
	"header": {
		"uploadTime" : {{timestamp.epoch}},	
		"networkIdentifier": "{{DeviceInfo.SerialNumber}}",
		"customerIdentifier": "Proximus-Tests"
	},
	"node_info": [
{{#partial_list.nodeinfo_json_tpl}}	{{! dont modify this object partial_list - internally generated by data-collector 
										partial_list object contains one or several lists, whose name equal to the partial template filename
										where '.' has replaced by '_' }}
		{{! pass 1 : resolve filename for each partial_list element }}
		{{! pass 2 : resolve partial : insert the content of filename }}
		((> {{&filename}} ))
{{/partial_list.nodeinfo_json_tpl}}
	],
	"reboot_events" : [
{{#partial_list.rhc_reboot_json_tpl}}	{{! dont modify this object partial_list - internally generated by data-collector 
											partial_list object contains one or several lists, whose name equal to the partial template filename
											where '.' has replaced by '_' }}
		{{! pass 1 : resolve filename for each partial_list element }}
		{{! pass 2 : resolve partial : insert the content of filename }}
		((> {{&filename}} ))
{{/partial_list.rhc_reboot_json_tpl}}
	],
	"system_logs" : [
{{#partial_list.rhc_system_json_tpl}}
		((> {{&filename}} ))
{{/partial_list.rhc_system_json_tpl}}
	],
	"temperature_logs" : [
	],
	"voice_logs" : [
	],
	"wan_info" : {
		"nodeIMEI" : "{{DeviceInfo.SerialNumber}}",
		"type" : ((#Link.<<@Link.*.Alias=FTTH_DATA@>>.Status=UP))"FTTH_ETHERNET",((/Link.<<@Link.*.Alias=FTTH_DATA@>>.Status=UP))
			((#Link.<<@Link.*.Alias=FTTH_DATA@>>.Status=!UP))
			((#Link.<<@Link.*.Alias=VDSL_DATA@>>.Status=UP))"VDSL",((/Link.<<@Link.*.Alias=VDSL_DATA@>>.Status=UP))
			((#Link.<<@Link.*.Alias=VDSL_DATA@>>.Status=!UP))
			((#Link.<<@Link.*.Alias=ETHOA_DATA@>>.Status=UP))"ADSL",((/Link.<<@Link.*.Alias=ETHOA_DATA@>>.Status=UP))
			((#Link.<<@Link.*.Alias=ETHOA_DATA@>>.Status=!UP))"UNKNOWN",((/Link.<<@Link.*.Alias=ETHOA_DATA@>>.Status=!UP))
			((/Link.<<@Link.*.Alias=VDSL_DATA@>>.Status=!UP))
			((/Link.<<@Link.*.Alias=FTTH_DATA@>>.Status=!UP))
		"interfaceName" : "{{Interface.0.IfcName}}",
		"ipv4Addresses": [
{{#Interface.0.IPv4Addresses.IPv4Address}}
{{#Status=ENABLED}}
			{
				"IPAddress": "{{IPAddress}}"
			}
{{/Status=ENABLED}}
{{/Interface.0.IPv4Addresses.IPv4Address}}
		],
		"ipv6Addresses": [
{{#Interface.0.IPv6Addresses.IPv6Address}}
{{#Status=ENABLED}}
			{
				"IPAddress": "{{IPAddress}}"
			}
{{/Status=ENABLED}}
{{/Interface.0.IPv6Addresses.IPv6Address}}
		],
		"wanInterfaceEventLogs":[
{{#partial_list.rhc_wan_itf_json_tpl}}
		((> {{&filename}} ))
{{/partial_list.rhc_wan_itf_json_tpl}}
		]
	},

	"backhaul_list" : [
	],

	"stations_list" : [
{{#partial_list.rhc_stations_list_json_tpl}}
		((> {{&filename}} ))
{{/partial_list.rhc_stations_list_json_tpl}}
	]
}
