#!/bin/sh /etc/rc.common
# Copyright (C) 2011 Sagemcom
START=10

. /etc/sysdirs.conf

start() {
	echo Check restore default by button

	/bin/check_reset
	
	if [ $? -eq 1 ]; then
		echo Doing restore default 
		/bin/restore_default
	fi

	echo Check restore default by flags

	if [ -f $SYSCONF_DIR/conf_erased ]; then
        rm -fr $SYSCONF_DIR/backup* 2> /dev/null
        find /opt/filesystem2/rootfs -type f | xargs rm -f
        find /opt/filesystem2/rootfs -type l | xargs rm -f
	fi

	if [ -f /opt/data/new-conf.xml ]; then
		mv /opt/data/new-conf.xml $SYSCONF_DIR/backup-cfg.xml
	fi

	rm $SYSCONF_DIR/conf_erased 2> /dev/null
}

stop() {
	echo Nothing to do!
}

